### ISSUE TITLE
User Story 8: Favorite Listing Page

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/Capstone-demo#13]
## Value Proposition

**As a** user 
**I want to** see a comprehensive list of all my Products
**so that**I can have an overview of all of my favorites.

## Description

A  list of all my favorite Products
​

## Acceptance Criteria

- [ ] Clicking the "Favorite" shows the Favorites Page
- [ ] All favorite art products are displayed as a list 
- [ ] Each product's image is displayed 
- [ ] Each product's title is displayed 
- [ ] Each product can remove from the list

## Tasks

- [ ] Pass the list of all favorite products via prop 
- [ ] render all favorite products in favorite page

      

## Complexity

... (T-Shirt Sizes XS to XL)
