### ISSUE TITLE
User Story 9: Checkout Page

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/Capstone-demo#15]
## Value Proposition

**As a** User 
**I want to**see a summary of my order, including the items I have added to my cart, the total cost.
**so that**I can confirm my order again and pay.
​

## Description
All of the orders can be showed in a list, a total price is displayed

## Acceptance Criteria

- [ ] A list for the order is displayed
- [ ] The total price is displayed
- [ ] A "Pay" button is displayed
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

... (T-Shirt Sizes XS to XL)
