### ISSUE TITLE
User Story 3: Shopping Cart Page

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/Capstone-demo#6]
## Value Proposition

**As a** user
**I want to** see all products, that I want to buy. I can see a total cost of all products. I can also remove a product from the list. I can also see the total price for all of my products.
**so that** I can see all products what I bought and remove the products what i don't need. 
​

## Description

A list for all products is displayed, instead of shopping cart button is a delete button displayed, 
The total price of all products are automatic calculated
Clicking the delete button on a product removes it from shopping cart Page and the total price can change automatic

## Acceptance Criteria

- [ ] All products, that the users bought, are displayed as a list 
- [ ] Each product’s image is displayed
- [ ] Each product’s description is displayed
- [ ] Each product’s price is displayed
- [ ] Instead of shopping cart button is a delete button displayed
- [ ] A counter is displayed
- [ ] The total price of all products are automatic calculated
- [ ] The total price can change automatic 
- [ ] Clicking the delete button on a product removes it from shopping cart Page
- [ ] A "checkout“ button is displayed

      ​

## Tasks

- [ ] create the remove button
- [ ] write a delete function for the remove button in global context
- [ ] total amount and total price should be changed
- [ ] styling the button and checkout area 
      ​

## Complexity

 L
