### ISSUE TITLE
Use Story 4: Thanks Page

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/Capstone-demo#7]
## Value Proposition

**As a** user
**I want to** review my orders.
**so that** I can see what I’ve purchased
​

## Description

​
![Bildschirm­foto 2023-03-21 um 17 41 59](https://user-images.githubusercontent.com/123374532/226681985-82300d0f-4af6-4366-a27d-9f9fd1caf1c7.png)

## Acceptance Criteria

- [ ] A list of orders is displayed
- [ ] A total cost is displayed
- [ ] A thanks text is displayed
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

... (T-Shirt Sizes XS to XL)
