### ISSUE TITLE
User Story 5: Search bar

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/Capstone-demo#8]
## Value Proposition

**As a** user
**I want to** find a product quickly
**so that** I can find the useful information
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] A search bar is on Header displayed
- [ ] Users can input text in the search bar
- [ ] Create a function
- [ ] All products with "keyword" are displayed
      ​

## Tasks

- [ ] create a search bar
- [ ] styling the search bar
- [ ] use "filter array method"
      ​

## Complexity

S
