### ISSUE TITLE
User Story 6: Nav bar 

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/Capstone-demo#9]
## Value Proposition

**As a** user
**I want to** see a nav bar on the page
**so that** I can easily navigate through the website
​
## Description

​![Bildschirm­foto 2023-03-22 um 19 56 05](https://user-images.githubusercontent.com/123374532/227008662-d6d595b9-43da-4b44-825b-2a111c9282cb.png)

## Acceptance Criteria

- [ ] A navigation link labeled "Homepage" is displayed
- [ ] A navigation link labeled "favorite" is displayed
- [ ] A navigation link labeled "shopping cart" is displayed
- [ ] A navigation link labeled "profil" is displayed
- [ ] Clicking "favorite" shows the Favorite Page
- [ ] Clicking "Shopping cart" shows the Shopping cart Page
- [ ] Clicking "Profil" shows the Profil Page
- [ ] Clicking "Home" shows the HomePage
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

... (T-Shirt Sizes XS to XL)
